energetica2030/energetica2030/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userHandler.urls')),
    path('', include('home.urls')),
    path('', include('viability.urls')),
    path('', include('operation.urls')),
]

energetica2030/home/urls.py
from django.urls import path
from .views import homePage

app_name='main'
urlpatterns = [
    path('', homePage, name='homePage'),
    path('home/', homePage, name='homePage'),
]

energetica2030/operation/urls.py
from django.urls import path
from .views import operationPage

app_name = 'operation'
urlpatterns = [
    path('operation/', operationPage, name='operationPage'),
]

energetica2030/userHandler/urls.py
from django.urls import path
from .views import signUpPage, logInPage, logOut

app_name='userHandler'
urlpatterns = [
    path('signUp/', signUpPage, name='signUpPage'),
    path('logIn/', logInPage, name='logInPage'),
    path('logOut/', logOut, name='logOut')
]

energetica2030/viability/urls.py
from django.urls import path
from .views import viabilityPage

app_name = 'viability'
urlpatterns = [
    path('viability/', viabilityPage, name='viabilityPage'),
]

energetica2030/home/models.py
from django.db import models

# Create your models here.

energetica2030/home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required(login_url='/logIn/')
#This function renders the home page that will allow the user to see the information about the project itself, also, from this page the user is able to navigate between the different tabs (viability and operation)
def homePage(request):
    return render(request, 'home/homePage.html', context={})

energetica2030/home/templates/includes/navbar.html
<div class="navbar-container">
    <a class="navbar-container__link navbar-container__link--home"href="{% url 'main:homePage' %}" style="text-decoration: none; color: #fff;">Home</a>
    <a class="navbar-container__link navbar-container__link--viablity"href="{% url 'viability:viabilityPage' %}" style="text-decoration: none; color: #fff;">Viabilidad</a>
    <a class="navbar-container__link navbar-container__link--operation"href="{% url 'operation:operationPage' %}" style="text-decoration: none; color: #fff;">Operación</a>
    <a class="navbar-container__link navbar-container__link--logOut"href="{% url 'userHandler:logOut' %}" style="text-decoration: none; color: #fff;" class="navbar-container__last">Cerrar Sesión</a>  
</div>